### ISSUE TITLE
Crash when logging into the server 1.20.1 Fabric

### ISSUE THREAD

**Issue by papillo12** [squeeglii/SimpleVoiceChat-Wiretap#2]
**Bug description**

**Steps to reproduce the issue**
I installed simple voice chat and wiretap on the server and simple voice chat on the client, started the server and when trying to enter the server it crashes.

**Expected behavior**
Crash

**Log files**
[latest.log](https://github.com/squeeglii/SimpleVoiceChat-Wiretap/files/14518004/latest.log)

[crash-2024-03-07_02.07.03-server.txt](https://github.com/squeeglii/SimpleVoiceChat-Wiretap/files/14517890/crash-2024-03-07_02.07.03-server.txt)
[crash-2024-03-07_02.16.56-server.txt](https://github.com/squeeglii/SimpleVoiceChat-Wiretap/files/14517892/crash-2024-03-07_02.16.56-server.txt)
[crash-2024-03-07_02.04.07-server.txt](https://github.com/squeeglii/SimpleVoiceChat-Wiretap/files/14517893/crash-2024-03-07_02.04.07-server.txt)

**Versions**
- 1.20.1
- 0.15.7
- the latest version of wiretap for 1.20.1 and first I used Simple Voice Chat 1.20.1-2.5.7 and since it didn't work then I used Simple Voice Chat 1.20.1-2.4.26 to see if a version closer to the month it was released would work.

**Comment by squeeglii** [comment]
Was the world fresh or reused from somewhere else? I couldn't recreate this on a fresh server + client but ran into a few other issues on the way.

**Comment by papillo12** [comment]
Well, I don't know what the mod was, as since I posted this I have made several changes to the modpack. Now I tested it and it works. Taking advantage of the occasion, could you tell me if it is possible to use several speakers working with a single microphone or if I should place several microphones and several speakers?

**Comment by papillo12** [comment]
Thanks

**Comment by squeeglii** [comment]
Aight well - I'll close the issue for now then. 

The microphones and speakers work in a one-to-one way so multiple microphones / speakers will not work sadly. I'll look into adding support for that in a future version.
